import Head from 'next/head'
import Image from 'next/image'
import Stock from '../components/Stock'
//import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className="flex justify-center items-center h-screen w-full">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>



      {/* george */}

      <Stock/>

      {/* <p className="text-red-500">hello world!</p> */}
    </div>
  )
}
